# You can use Placeholder API placeholders in these messages. To do so put the placeholder like <papi:placeholder> so for
# something like %player_username% you would do <papi:player_username> instead.
# Provided placeholders are <displayname> for display name, and <username> for user name
format:
  normal: "<displayname>"
  social-spy: "<username>"
  # Other messages can be configured in locale.yml
mysql:
  enabled: false
  ip: "localhost:3306"
  name: homes
  username: username1
  password: badpassword!
allow-messaging:
  hidden-players: false
  console: true
valid-console-names:
  - server
  - console
# This sends a specific message to console with the same socialspy format.
# Useful for searching logs, but also may cause clutter
console-has-social-spy: true
console-has-command-spy: false
command-spy:
  enabled: false
  commands: # have social spy also spy on these commands:
    - /minecraft:w
    - /minecraft:tell
    - /minecraft:msg
    - /minecraft:say
    - /minecraft:me
    - /minecraft:op
    - /op
    - /gmc
    - /gamemode
    - /give
