#

#
mysql:
  enabled: false
  ip: "localhost:3306"
  name: homes
  username: username1
  password: badpassword!
allow-messaging:
  hidden-players: false
  console: true
valid-console-names:
  - server
  - console
# This sends a specific message to console with the same socialspy format.
# Useful for searching logs, but also may cause clutter
console-has-social-spy: true