#
mysql:
  enabled: false
  ip: "localhost:3306"
  name: homes
  username: username1
  password: badpassword!
allow-messaging:
  hidden-players: false
  console: true
valid-console-names:
  - server
  - console