name: SimplePMs
version: '${project.version}'
main: simplexity.simplepms.SimplePMs
api-version: 1.20.6
description: Plugin focused on simple private messaging.
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
