name: SimplePMs
version: '${project.version}'
main: simplexity.simplepms.SimplePMs
api-version: 1.19
authors: [ Rhythmic, Peashooter101 ]
description: Plugin focused on simple private messaging.
softdepend:
  - PlaceholderAPI
commands:
  msg:
    description: "Allows the user to send a private message to someone."
    aliases: [dm, m, pm, tell, t]
    permission: spm.message.send
  reply:
    description: "allows the user to reply to a private message"
    aliases: [r, re]
    permission: spm.message.send
  socialspy:
    description: "toggles socialspy"
    aliases: [ss, spy, sspy]
    permission: spm.socialspy.toggle
  spmreload:
    description: "reloads SimplePMs"
    permission: spm.reload
permissions:
