name: SimplePMs
version: '${project.version}'
main: simplexity.simplepms.SimplePMs
api-version: 1.20.6
authors: [ Rhythmic, Peashooter101 ]
description: Plugin focused on simple private messaging.
softdepend:
  - PlaceholderAPI
commands:
  msg:
    description: "Allows the user to send a private message to someone."
    aliases: [tell, w]
    permission: message.basic.send
  msgtoggle:
    description: "Toggles direct messages for the user"
    permission: message.basic.toggle
  reply:
    description: "allows the user to reply to a private message"
    aliases: [r]
    permission: message.basic.send
  block:
    description: "Blocks a user from direct-messaging you"
    permission: message.basic.block
  unblock:
    description: "Unblocks a user you have blocked"
    permission: message.basic.block
  blocklist:
    description: "Lists the players you have blocked and the reasons"
    permission: message.basic.block
  socialspy:
    description: "toggles socialspy"
    aliases: [ss]
    permission: message.admin.social-spy
  spmreload:
    description: "reloads SimplePMs"
    permission: message.reload
permissions:
  message.basic:
    default: true
    description: Base permission for basic functionality
    children:
      message.basic.send: true
      message.basic.receive: true
      message.basic.toggle: true
      message.basic.block: true
  message.basic.send:
    default: true
    description: Allows sending messages
  message.basic.receive:
    default: true
    description: Allows receiving messages
  message.basic.toggle:
    default: true
    description: Allows enabling/disabling direct messages
  message.basic.block:
    default: true
    description: Allows blocking direct messages from and to specific users
  message.reload:
    default: op
    description: reloads the config and locale
  message.admin:
    default: op
    description: Base permission for the admin commands
    children:
      message.admin.override: true
      message.admin.social-spy: true
      message.admin.console-spy: true
  message.admin.override:
    default: op
    description: Allows messaging someone who has their messages currently disabled, has you blocked or does not have permissions to usually see messages
  message.admin.social-spy:
    default: op
    description: Shows the direct messages of other players for moderation purposes
  message.admin.console-spy:
    default: op
    description: Shows the direct messages sent to and from the console sender (from this plugin) to other players
  message.bypass.social-spy:
    default: op
    description: Prevents messages to and from you from showing in social spy, does not prevent the formatted console spy message
  message.bypass.command-spy:
    default: op
    description: Stops your commands from being shown to others with command spy (if they are configured to be tracked). Does not prevent the formatted console spy message
